apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRZGxKeG8rR3UzUFo0ZWo3L0lBSUxIakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGt3T0RFM01qQXdPVm9YRFRNMU1Ea3dOakUzTWpBdwpPVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCS2ppcjVYNTBNcGxkcTBrdEZLLzRqaGFnZnRTaC84TVFldVZsc0RUT09Wa05rN0FyVEU1bUFiTmVzZ0cKa0wyYndjdWY0SkIycVl4M3ljOXc5dEg3VjdtallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVLa2dsa1AwcFQ2V2kxU1o4NzBPTFQwSFloS0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU81M2VpY1kKNFlwVkhFaVlUbGFaL3Jubis1a25yMnc0Y0JPN0ZzNEJFYUcxQWlBWFJMYmtIMDMxZG1ZTS90NDJQeHVmVDlLQwo0TXdQU2d6bW92UFhTVzMxUXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://65.109.223.169:6443
  name: h.kibaship.app
contexts:
- context:
    cluster: h.kibaship.app
    namespace: default
    user: admin@h.kibaship.app
  name: admin@h.kibaship.app
current-context: admin@h.kibaship.app
kind: Config
users:
- name: admin@h.kibaship.app
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVNxZ0F3SUJBZ0lRSHJ4Y21sM1hXQnVBaWFScFVkYzFpREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGt3T0RFNE1UYzFNRm9YRFRJMk1Ea3dPREU0TVRndwpNRm93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSTNIeVV0U3FrUXlIOWd6bjZsSVBhQXZhMzlzVm5jaTEKNXdkOTlyb010NmQycEtYT2ZkSWtKOWdjZEh3R0Y3cmc2V0ZtcllMN0pkd292dHdXMW5KNThhTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGQ3BJCkpaRDlLVStsb3RVbWZPOURpMDlCMklTaE1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRGNiZW0xenlaVFBnNUsKOTY1RmIrTmgxNUVTVm5GK01hcCtBOUpnSHBiaHJBSWhBSm05eVZ1RzFxWVN4RmZFakgvUWthZzdmcC9abzJkUApEWGhtZGxwRUt2ek4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURKRk16anpobzlaeWhpWG9WNFgxN0ZsVElnWHJ3bFNoY05qVnFnN0xJNHpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSTNIeVV0U3FrUXlIOWd6bjZsSVBhQXZhMzlzVm5jaTE1d2Q5OXJvTXQ2ZDJwS1hPZmRJawpKOWdjZEh3R0Y3cmc2V0ZtcllMN0pkd292dHdXMW5KNThRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
