apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-auth
  namespace: registry
  labels:
    app: registry-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry-auth
  template:
    metadata:
      labels:
        app: registry-auth
    spec:
      serviceAccountName: registry-auth
      containers:
        - name: registry-auth
          image: registry-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: auth-keys
              mountPath: /etc/registry-auth-keys
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
      volumes:
        - name: auth-keys
          secret:
            secretName: registry-auth-keys
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt