apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
images:
- name: registry-auth
  newName: kibamail/kibaship-operator-registry-auth
  newTag: v0.1.6
