apiVersion: v1
kind: Service
metadata:
  name: registry-auth
  namespace: registry
  labels:
    app: registry-auth
spec:
  selector:
    app: registry-auth
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP