apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.dns.kibaship.com
  annotations:
    cert-manager.io/inject-ca-from: kibaship/kibaship-dns01-webhook-cert
spec:
  group: dns.kibaship.com
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kibaship-cert-manager-webhook
    namespace: kibaship
    port: 443
  insecureSkipTLSVerify: false
