apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kibaship
  labels:
    app.kubernetes.io/name: kibaship-cert-manager-webhook
    app.kubernetes.io/part-of: kibaship
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibaship-dns01-webhook-cert
  namespace: kibaship
  labels:
    app.kubernetes.io/name: kibaship-cert-manager-webhook
    app.kubernetes.io/part-of: kibaship
spec:
  dnsNames:
    - kibaship-cert-manager-webhook.kibaship.svc
    - kibaship-cert-manager-webhook.kibaship.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kibaship-dns01-webhook-tls
