# # from https://github.com/moby/buildkit/tree/a038b5d98379646995275830a4f778bc707b2356/examples/kubernetes
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: buildkitd
#   namespace: buildkit
#   labels:
#     app: buildkitd
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: buildkitd
#   template:
#     metadata:
#       labels:
#         app: buildkitd
#       annotations:
#         container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
#         container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
#     spec:
#       containers:
#         - name: buildkitd
#           image: moby/buildkit:v0.24.0-rootless
#           args:
#             - --addr
#             - unix:///run/user/1000/buildkit/buildkitd.sock
#             - --addr
#             - tcp://0.0.0.0:1234
#             - --oci-worker-no-process-sandbox
#           securityContext:
#             # To change UID/GID, you need to rebuild the image
#             runAsUser: 1000
#             runAsGroup: 1000
#           ports:
#             - containerPort: 1234
#           volumeMounts:
#             - name: certs
#               readOnly: true
#               mountPath: /certs

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: buildkit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.24.0-rootless
          args:
            - --addr
            - unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --oci-worker-no-process-sandbox
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 1234
