version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - lll
        path: test/.*
      - linters:
          - lll
        path: pkg/handlers/.*
      - linters:
          - lll
        path: pkg/models/.*
      - linters:
          - lll
        path: pkg/services/.*
      - linters:
          - lll
        path: pkg/templates/.*
      - linters:
          - dupl
        path: test/.*
      - linters:
          - dupl
        path: pkg/handlers/.*
      - linters:
          - dupl
        path: pkg/services/.*
      - linters:
          - dupl
        path: pkg/templates/.*

    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
