[all]
default-control-plane-1 ansible_user=ubuntu ansible_host=10.0.1.10 ip=10.0.1.10 etcd_member_name=etcd1
default-control-plane-2 ansible_user=ubuntu ansible_host=10.0.1.11 ip=10.0.1.11 etcd_member_name=etcd2
default-control-plane-3 ansible_user=ubuntu ansible_host=10.0.1.12 ip=10.0.1.12 etcd_member_name=etcd3
default-worker-1 ansible_user=ubuntu ansible_host=10.0.1.20 ip=10.0.1.20
default-worker-2 ansible_user=ubuntu ansible_host=10.0.1.21 ip=10.0.1.21
default-worker-3 ansible_user=ubuntu ansible_host=10.0.1.22 ip=10.0.1.22

[kube_control_plane]
default-control-plane-1
default-control-plane-2
default-control-plane-3

[etcd]
default-control-plane-1
default-control-plane-2
default-control-plane-3

[kube_node]
default-worker-1
default-worker-2
default-worker-3

[k8s_cluster:children]
kube_control_plane
kube_node
