[kube_control_plane]
k8s-cp-1 ansible_host=129.212.190.178 ip=10.219.0.6 access_ip=129.212.190.178
k8s-cp-2 ansible_host=134.199.200.128 ip=10.219.0.8 access_ip=134.199.200.128
k8s-cp-3 ansible_host=134.199.200.113 ip=10.219.0.5 access_ip=134.199.200.113

[kube_node]
k8s-worker-1 ansible_host=129.212.186.163 ip=10.219.0.9 access_ip=129.212.186.163
k8s-worker-2 ansible_host=129.212.181.110 ip=10.219.0.7 access_ip=129.212.181.110
k8s-worker-3 ansible_host=129.212.182.158 ip=10.219.0.4 access_ip=129.212.182.158

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no'

kube_control_plane_endpoint=kube.pangaso.kibaship.com

kube_load_balancer_public_ip=134.199.133.170
kube_load_balancer_private_ip=134.199.133.170

ingress_control_plane_endpoint=pangaso.kibaship.com
ingress_load_balancer_public_ip=134.199.132.48

ingress_load_balancer_private_ip=134.199.132.48

cluster_name=pangaso.kibaship.com

kube_service_addresses=10.219.0.0/16
kube_pods_subnet=10.244.0.0/16
dns_domain=cluster.local