apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace for Tekton resources - they must be in tekton-pipelines namespace
namespace: tekton-pipelines

# Tekton resources for KibaShip operator

resources:
- tasks/platform.operator.kibaship.com_git_clone_tasks.yaml
- tasks/platform.operator.kibaship.com_railpack_prepare_tasks.yaml
- tasks/platform.operator.kibaship.com_railpack_build_tasks.yaml
- tasks/platform.operator.kibaship.com_dockerfile_build_tasks.yaml

# Labels to add to all Tekton resources
labels:
- pairs:
    app.kubernetes.io/component: tekton-integration
    app.kubernetes.io/managed-by: kibaship
    app.kubernetes.io/name: kibaship
images:
- name: kibamail/kibaship-railpack-build
  newName: kibamail/kibaship-railpack-build
  newTag: e2e
- name: kibamail/kibaship-railpack-cli
  newName: kibamail/kibaship-railpack-cli
  newTag: e2e
