apiVersion: v1
kind: Service
metadata:
  name: acme-dns
  namespace: kibaship
  labels:
    app: acme-dns
    app.kubernetes.io/name: acme-dns
    app.kubernetes.io/component: dns
    app.kubernetes.io/managed-by: kibaship
spec:
  type: ClusterIP
  selector:
    app: acme-dns
  ports:
    # DNS port - UDP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    # DNS port - TCP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    # HTTP API port
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
