---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    role_path: "{{ playbook_dir }}/../.."
    k8s_networking_sysctl_file: "/etc/sysctl.d/99-kubernetes-networking.conf"
    k8s_networking_bridge_sysctls:
      - name: "net.bridge.bridge-nf-call-iptables"
        value: "1"
      - name: "net.bridge.bridge-nf-call-arptables" 
        value: "1"
      - name: "net.bridge.bridge-nf-call-ip6tables"
        value: "1"

  tasks:
    - name: Include k8s_node_networking role directly with templates
      include_tasks: ../../tasks/main.yml