apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry-auth
    newName: kibaship.com/kibaship-operator-registry-auth
    newTag: v0.0.1