apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-replica-rwx
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  # Enable ReadWriteMany access mode
  migratable: "true"
