---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Start etcd service
  systemd:
    name: etcd
    state: started
    enabled: true
  when: etcd_service_enabled | default(false)

- name: Restart etcd service
  systemd:
    name: etcd
    state: restarted
  when: etcd_service_enabled | default(false)