[kube_control_plane]
k8s-cp-1 ansible_host=134.122.22.196 ip=10.219.0.7 access_ip=134.122.22.196
k8s-cp-2 ansible_host=137.184.72.77 ip=10.219.0.4 access_ip=137.184.72.77
k8s-cp-3 ansible_host=68.183.124.75 ip=10.219.0.9 access_ip=68.183.124.75

[kube_node]
k8s-worker-1 ansible_host=192.81.217.248 ip=10.219.0.8 access_ip=192.81.217.248
k8s-worker-2 ansible_host=104.248.113.138 ip=10.219.0.5 access_ip=104.248.113.138
k8s-worker-3 ansible_host=142.93.15.192 ip=10.219.0.6 access_ip=142.93.15.192

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no'

kube_control_plane_endpoint=kube.sha.kibaship.com

kube_load_balancer_public_ip=143.244.202.140
kube_load_balancer_private_ip=143.244.202.140

ingress_control_plane_endpoint=sha.kibaship.com
ingress_load_balancer_public_ip=129.212.137.112

ingress_load_balancer_private_ip=129.212.137.112

cluster_name=sha.kibaship.com

kube_service_addresses=10.219.0.0/16
kube_pods_subnet=10.244.0.0/16
dns_domain=cluster.local