# This rule is not used by the project kibaship-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over platform.operator.kibaship.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kibaship-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-admin-role
rules:
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - projects/status
  verbs:
  - get
