# TODO: Database application manifests removed - will be reimplemented
# MySQL, Valkey, and Postgres application manifests have been removed

# Docker Image Application
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  name: application-docker-image
  namespace: e2e-test-project
  labels:
    platform.kibaship.com/uuid: "docker-image-uuid"
    platform.kibaship.com/slug: "application-docker-image"
    platform.kibaship.com/project-uuid: "e2e-test-uuid"
    platform.kibaship.com/workspace-uuid: "workspace-e2e-test"
    platform.kibaship.com/environment-uuid: "prod-env-uuid"
spec:
  type: DockerImage
  port: 80
  environmentRef:
    name: environment-production
  dockerImage:
    dockerfile: |
      FROM nginx:alpine
      COPY index.html /usr/share/nginx/html/
      EXPOSE 80
    env:
      name: application-docker-image
---
# Git Repository Application
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  name: application-git-repo
  namespace: e2e-test-project
  labels:
    platform.kibaship.com/uuid: "git-repo-uuid"
    platform.kibaship.com/slug: "application-git-repo"
    platform.kibaship.com/project-uuid: "e2e-test-uuid"
    platform.kibaship.com/workspace-uuid: "workspace-e2e-test"
    platform.kibaship.com/environment-uuid: "prod-env-uuid"
spec:
  type: GitRepository
  port: 3000
  environmentRef:
    name: environment-production
  gitRepository:
    url: "https://github.com/example/sample-app.git"
    branch: "main"
    dockerfile: |
      FROM node:18-alpine
      WORKDIR /app
      COPY package*.json ./
      RUN npm ci --only=production
      COPY . .
      EXPOSE 3000
      CMD ["node", "server.js"]
    env:
      name: application-git-repo
---
# Image From Registry Application
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  name: application-image-registry
  namespace: e2e-test-project
  labels:
    platform.kibaship.com/uuid: "image-registry-uuid"
    platform.kibaship.com/slug: "application-image-registry"
    platform.kibaship.com/project-uuid: "e2e-test-uuid"
    platform.kibaship.com/workspace-uuid: "workspace-e2e-test"
    platform.kibaship.com/environment-uuid: "prod-env-uuid"
spec:
  type: ImageFromRegistry
  port: 80
  environmentRef:
    name: environment-production
  imageFromRegistry:
    image: "nginx:latest"
