apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  namespace: kibaship-operator
  labels:
    app: webhook-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
        - name: receiver
          image: python:3.11-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command:
            - /bin/sh
            - -c
            - |
              cat <<'PY' >/tmp/receiver.py
              import http.server
              import json

              class Handler(http.server.BaseHTTPRequestHandler):
                  def do_POST(self):
                      length = int(self.headers.get('Content-Length', '0'))
                      body_bytes = self.rfile.read(length)

                      # Try to parse JSON body; fall back to UTF-8 string if not JSON
                      body_obj = None
                      try:
                          body_obj = json.loads(body_bytes)
                      except Exception:
                          try:
                              body_obj = json.loads(body_bytes.decode('utf-8', 'ignore'))
                          except Exception:
                              body_obj = body_bytes.decode('utf-8', 'ignore')

                      event = {
                          'method': 'POST',
                          'path': self.path,
                          'headers': {k: v for k, v in self.headers.items()},
                          'body': body_obj,
                      }
                      print(json.dumps(event, indent=2, sort_keys=True, ensure_ascii=False), flush=True)
                      self.send_response(200)
                      self.send_header('Content-Type', 'text/plain')
                      self.end_headers()
                      self.wfile.write(b'ok\n')

                  def log_message(self, *args, **kwargs):
                      pass

              if __name__ == '__main__':
                  http.server.HTTPServer(('0.0.0.0', 8080), Handler).serve_forever()
              PY
              exec python -u /tmp/receiver.py
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: kibaship-operator
  labels:
    app: webhook-receiver
spec:
  selector:
    app: webhook-receiver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
