---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include defaults from role
      include_vars: ../../defaults/main.yml
    
    - name: Include etcd_install role tasks
      include_tasks: ../../tasks/main.yml