---
- name: Converge
  hosts: all
  become: false  # Run as root in container directly
  gather_facts: false

  tasks:
    - name: Include os_prep_packages role directly
      include_tasks: ../../tasks/main.yml