[kube_control_plane]
k8s-cp-1 ansible_host=134.199.197.151 ip=10.0.0.6 access_ip=134.199.197.151
k8s-cp-2 ansible_host=129.212.180.190 ip=10.0.0.9 access_ip=129.212.180.190
k8s-cp-3 ansible_host=129.212.189.231 ip=10.0.0.7 access_ip=129.212.189.231

[kube_node]
k8s-worker-1 ansible_host=129.212.180.32 ip=10.0.0.5 access_ip=129.212.180.32
k8s-worker-2 ansible_host=134.199.207.65 ip=10.0.0.4 access_ip=134.199.207.65
k8s-worker-3 ansible_host=129.212.188.110 ip=10.0.0.8 access_ip=129.212.188.110

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no'

kube_control_plane_endpoint=kube.sha.kibaship.com

kube_load_balancer_public_ip=134.199.133.193
kube_load_balancer_private_ip=134.199.133.193

ingress_control_plane_endpoint=sha.kibaship.com
ingress_load_balancer_public_ip=134.199.133.192

ingress_load_balancer_private_ip=134.199.133.192

cluster_name=sha.kibaship.com

kube_service_addresses=10.96.0.0/12
kube_pods_subnet=10.244.0.0/16
dns_domain=cluster.local