## Append samples of your project ##
resources:
- platform_v1alpha1_project.yaml
- platform_v1alpha1_application.yaml
- platform_v1alpha1_deployment.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
