# GitRepository Application with all available fields
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: kibaship
    app.kubernetes.io/managed-by: kustomize
    platform.kibaship.com/uuid: "550e8400-e29b-41d4-a716-446655440001"
  name: application-sample-gitrepo-full
  namespace: default
spec:
  projectRef:
    name: my-project
  type: GitRepository
  gitRepository:
    provider: github.com
    repository: myorg/myapp
    branch: main
    path: "/backend"
    rootDirectory: "./"
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    spaOutputDirectory: "dist"
    secretRef:
      name: git-access-token
    env:
      name: app-env-secret
---
# GitRepository Application with minimal required fields (using defaults)
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: kibaship
    app.kubernetes.io/managed-by: kustomize
    platform.kibaship.com/uuid: "550e8400-e29b-41d4-a716-446655440002"
  name: application-sample-gitrepo-minimal
  namespace: default
spec:
  projectRef:
    name: my-project
  type: GitRepository
  gitRepository:
    provider: gitlab.com
    repository: myorg/simple-app
    secretRef:
      name: git-access-token
    # rootDirectory defaults to "./"
    # buildCommand, startCommand, and env are optional
---
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: kibaship
    app.kubernetes.io/managed-by: kustomize
    platform.kibaship.com/uuid: "550e8400-e29b-41d4-a716-446655440003"
  name: application-sample-docker
  namespace: default
spec:
  projectRef:
    name: my-project
  type: DockerImage
  dockerImage:
    image: nginx:1.21
    imagePullSecretRef:
      name: docker-registry-secret
---
# TODO: Database application samples removed - will be reimplemented
# MySQL, MySQLCluster, Postgres, PostgresCluster, Valkey, ValkeyCluster samples removed
---
apiVersion: platform.operator.kibaship.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: kibaship
    app.kubernetes.io/managed-by: kustomize
    platform.kibaship.com/uuid: "550e8400-e29b-41d4-a716-446655440007"
  name: application-sample-postgres-cluster
  namespace: default
spec:
  projectRef:
    name: my-project
  type: PostgresCluster
  postgresCluster:
    version: "14"
    replicas: 3
    database: myapp
    secretRef:
      name: postgres-cluster-credentials
