apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: registry
spec:
  secretName: registry-tls
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - kibaship
  commonName: registry.registry.svc.cluster.local
  dnsNames:
    - registry.registry.svc.cluster.local
    - registry.registry.svc
    - registry.registry
    - registry
  privateKey:
    algorithm: RSA
    size: 4096
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: registry-selfsigned-issuer
    kind: Issuer