apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
  labels:
    app: registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
      level: debug
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      tls:
        certificate: /etc/registry-tls/tls.crt
        key: /etc/registry-tls/tls.key
    auth:
      token:
        realm: http://registry-auth.registry.svc.cluster.local/auth
        service: docker-registry
        issuer: registry-token-issuer
        rootcertbundle: /etc/registry-auth-keys/tls.crt
        jwks: /etc/registry-auth-keys-jwks/jwks.json
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
