apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      enableServiceLinks: false
      containers:
        - name: registry
          image: registry:3.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: https
              protocol: TCP
          volumeMounts:
            - name: registry-config
              mountPath: /etc/distribution
              readOnly: true
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: registry-tls
              mountPath: /etc/registry-tls
              readOnly: true
            - name: registry-auth-keys
              mountPath: /etc/registry-auth-keys
              readOnly: true
            - name: registry-auth-keys-jwks
              mountPath: /etc/registry-auth-keys-jwks
              readOnly: true
          env:
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: registry-registry-auth
                  key: http-secret
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
      serviceAccountName: registry
      volumes:
        - name: registry-config
          configMap:
            name: registry-config
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-storage
        - name: registry-tls
          secret:
            secretName: registry-tls
        - name: registry-auth-keys
          secret:
            secretName: registry-auth-keys
            items:
              - key: tls.crt
                path: tls.crt
        - name: registry-auth-keys-jwks
          secret:
            secretName: registry-auth-keys-jwks
