apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: registry
  labels:
    app: registry
spec:
  storageClassName: storage-replica-rwm-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi