apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - name: https
      port: 443
      targetPort: 5000
      protocol: TCP
  type: ClusterIP