apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kibaship-apiserver-crd-access
  labels:
    app.kubernetes.io/name: kibaship-apiserver
    app.kubernetes.io/managed-by: kustomize
rules:
  # Full management access to Kibaship Operator CRDs
  - apiGroups: ["platform.operator.kibaship.com"]
    resources: [
      "projects",
      "projects/status",
      "environments",
      "environments/status",
      "applications",
      "applications/status",
      "deployments",
      "deployments/status",
      "applicationdomains",
      "applicationdomains/status"
    ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

