apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kibaship-apiserver-crd-access
  labels:
    app.kubernetes.io/name: kibaship-apiserver
    app.kubernetes.io/managed-by: kustomize
subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: kibaship
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kibaship-apiserver-crd-access
