apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app.kubernetes.io/name: kibaship-apiserver
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: kibaship-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibaship-apiserver
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: apiserver
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: apiserver
          # Image will be replaced by kustomize: `kustomize edit set image apiserver=<repo>:<tag>`
          image: apiserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: GIN_MODE
              value: release
            - name: PORT
              value: "8080"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
