apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ensure all resources are created in the operator namespace
namespace: kibaship

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kibaship-apiserver

resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
images:
- name: apiserver
  newName: kibamail/kibaship-apiserver
  newTag: v1.0.0
