apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kibaship-operator.fullname" . }}-controller-manager
  namespace: {{ include "kibaship-operator.namespace" . }}
  labels:
    {{- include "kibaship-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      {{- include "kibaship-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "kibaship-operator.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: "{{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy }}
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        env:
        - name: KIBASHIP_OPERATOR_DOMAIN
          value: {{ .Values.operator.domain | quote }}
        - name: KIBASHIP_OPERATOR_DEFAULT_PORT
          value: {{ .Values.operator.defaultPort | quote }}
        {{- if .Values.debug.enabled }}
        - name: LOG_LEVEL
          value: {{ .Values.debug.level | quote }}
        {{- end }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.controllerManager.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: {{ include "kibaship-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "kibaship-operator.fullname" . }}-webhook-server-cert