# RBAC is always enabled for proper operator functionality
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kibaship-operator.fullname" . }}-manager-role
  labels:
    {{- include "kibaship-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applicationdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applicationdomains/finalizers
  verbs:
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applicationdomains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - platform.operator.kibaship.com
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.oracle.com
  resources:
  - innodbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - issuers
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperspike.io
  resources:
  - valkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kibaship-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "kibaship-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kibaship-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kibaship-operator.serviceAccountName" . }}
  namespace: {{ include "kibaship-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kibaship-operator.fullname" . }}-leader-election-role
  namespace: {{ include "kibaship-operator.namespace" . }}
  labels:
    {{- include "kibaship-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kibaship-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "kibaship-operator.namespace" . }}
  labels:
    {{- include "kibaship-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kibaship-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kibaship-operator.serviceAccountName" . }}
  namespace: {{ include "kibaship-operator.namespace" . }}
# End of RBAC configuration