# diskpools.yaml
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-on-worker-1
  namespace: openebs
spec:
  node: <worker-1-nodename> # The name of the node as seen in `kubectl get nodes`
  disks: # Replace with your disk's stable ID
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-on-worker-2
  namespace: openebs
spec:
  node: <worker-2-nodename>
  disks: # Replace with your disk's stable ID
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-on-worker-3
  namespace: openebs
spec:
  node: <worker-3-nodename>
  disks: # Replace with your disk's stable ID
