# Kibaship Kubernetes Cluster Inventory
# This is a sample inventory for a HA cluster with 3 control planes and 3 workers
# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# Set etcd_member_name for etcd cluster members

[kube_control_plane]
# node1 ansible_host=95.54.0.12  ip=10.3.0.1 etcd_member_name=etcd1
# node2 ansible_host=95.54.0.13  ip=10.3.0.2 etcd_member_name=etcd2
# node3 ansible_host=95.54.0.14  ip=10.3.0.3 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
# node4 ansible_host=95.54.0.15  ip=10.3.0.4
# node5 ansible_host=95.54.0.16  ip=10.3.0.5
# node6 ansible_host=95.54.0.17  ip=10.3.0.6

[k8s_cluster:children]
kube_control_plane
kube_node