apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../api-server

images:
  - name: apiserver
    newName: kibamail/kibaship-apiserver
    newTag: e2e

patches:
  # Reduce replicas to 1 for e2e tests
  - target:
      kind: Deployment
      name: apiserver
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
