---
# k8s_control_plane_join role handlers

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
  become: true
  when: container_manager == 'containerd'