name: Build and Push - Railpack CLI

on:
  workflow_run:
    workflows: [Tests, E2E Tests, Lint]
    types: [completed]
  push:
    tags: ["v*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kibamail/kibaship-railpack-cli

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.ref == 'refs/heads/main') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ startsWith(github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref, 'refs/tags/v') || startsWith(github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref, 'refs/heads/main') }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (railpack-cli)
        id: meta
        uses: docker/metadata-action@v5
        env:
          GITHUB_REF: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref }}
          GITHUB_SHA: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=short,prefix=sha-

      - name: Build and push Docker image (railpack-cli)
        uses: docker/build-push-action@v6
        with:
          context: build/railpack-cli
          file: build/railpack-cli/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref, 'refs/tags/v') || startsWith(github.event_name == 'workflow_run' && github.event.workflow_run.ref || github.ref, 'refs/heads/main') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

